
create database Customer_behavior;

use Customer_behavior;

select * from customer_shopping_behavior_v2_cleaned;

select top 10  * from [dbo].[customer_shopping_behavior_v2_cleaned];

-- 1) What is the total revenue generated by male vs female customers???

select gender, sum(purchase_amount) as revenue 
from customer_shopping_behavior_v2_cleaned 
group by gender;

-- 2) which customers used a discount but still spent more than the 
-- average purchase amount???

select customer_id, purchase_amount
from customer_shopping_behavior_v2_cleaned
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount)
from customer_shopping_behavior_v2_cleaned);

-- 3) which are the top 5 products with the highest average review rating???

select top 5 item_purchased, round(avg(review_rating),2) as 'Average Product Rating'
from customer_shopping_behavior_v2_cleaned
group by item_purchased
order by avg(review_rating) desc;

-- 4) Compare the average Purchase Amounts between Standard and Express Shipping???

select shipping_type,
round(avg(purchase_amount),2)
from customer_shopping_behavior_v2_cleaned
where shipping_type in ('Standard','Express')
group by shipping_type;

-- 5) Do subscribed customers spend more? Compare average spend and total 
-- revenue bewteen subscriber and non-subscribers???

select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer_shopping_behavior_v2_cleaned
group by subscription_status
order by total_revenue, avg_spend desc;

-- 6) Which 5 products have the highest percentage with discounts applied???

select top 5 item_purchased,
round(100 * sum(CASE when discount_applied = 'Yes' then 1 ELSE 0 END) /count(*),2) as discount_rate
from customer_shopping_behavior_v2_cleaned
group by item_purchased
order by discount_rate desc;

-- 7) Segment customers into New, Returning, and loyal based on their total
--number of previous purchases, and show the count of each segment???

with customer_type as (
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 then 'New'
	when previous_purchases BETWEEN 2 And 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer_shopping_behavior_v2_cleaned
)

select customer_segment, count(*) as 'Number of customers'
from customer_type
group by customer_segment;

-- 8) What are the top 3 most purchased products within each category???

with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
Row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer_shopping_behavior_v2_cleaned
group by category, item_purchased 
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <= 3;

-- 9) Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe??

select subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping_behavior_v2_cleaned
where previous_purchases > 5
group by subscription_status;

-- 10) what is the revenue contribution of each age group???

select age_groups,
sum(purchase_amount) as total_revenue
from customer_shopping_behavior_v2_cleaned
group by age_groups
order by total_revenue desc;